const { heroui } = require("@heroui/theme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "rgb(var(--primary-50-rgb) / <alpha-value>)",
          100: "rgb(var(--primary-100-rgb) / <alpha-value>)",
          200: "rgb(var(--primary-200-rgb) / <alpha-value>)",
          300: "rgb(var(--primary-300-rgb) / <alpha-value>)",
          400: "rgb(var(--primary-400-rgb) / <alpha-value>)",
          500: "rgb(var(--primary-500-rgb) / <alpha-value>)",
          600: "rgb(var(--primary-600-rgb) / <alpha-value>)",
          700: "rgb(var(--primary-700-rgb) / <alpha-value>)",
          800: "rgb(var(--primary-800-rgb) / <alpha-value>)",
          900: "rgb(var(--primary-900-rgb) / <alpha-value>)",
          DEFAULT: "rgb(var(--primary-rgb) / <alpha-value>)",
          foreground: "rgb(var(--primary-foreground-rgb) / <alpha-value>)",
        },
        secondary: {
          50: "rgb(var(--secondary-50-rgb) / <alpha-value>)",
          100: "rgb(var(--secondary-100-rgb) / <alpha-value>)",
          200: "rgb(var(--secondary-200-rgb) / <alpha-value>)",
          300: "rgb(var(--secondary-300-rgb) / <alpha-value>)",
          400: "rgb(var(--secondary-400-rgb) / <alpha-value>)",
          500: "rgb(var(--secondary-500-rgb) / <alpha-value>)",
          600: "rgb(var(--secondary-600-rgb) / <alpha-value>)",
          700: "rgb(var(--secondary-700-rgb) / <alpha-value>)",
          800: "rgb(var(--secondary-800-rgb) / <alpha-value>)",
          900: "rgb(var(--secondary-900-rgb) / <alpha-value>)",
          DEFAULT: "rgb(var(--secondary-rgb) / <alpha-value>)",
          foreground: "rgb(var(--secondary-foreground-rgb) / <alpha-value>)",
        },
        background: "rgb(var(--background-rgb) / <alpha-value>)",
        foreground: "rgb(var(--foreground-rgb) / <alpha-value>)",
        surface: {
          1: "rgb(var(--surface-1-rgb) / <alpha-value>)",
          2: "rgb(var(--surface-2-rgb) / <alpha-value>)",
          3: "rgb(var(--surface-3-rgb) / <alpha-value>)",
          4: "rgb(var(--surface-4-rgb) / <alpha-value>)",
          elevated: "rgb(var(--surface-elevated-rgb) / <alpha-value>)",
          foreground: "rgb(var(--surface-foreground-rgb) / <alpha-value>)",
          muted: "rgb(var(--surface-muted-rgb) / <alpha-value>)",
          border: "rgb(var(--surface-border-rgb) / <alpha-value>)",
          hover: "rgb(var(--surface-hover-rgb) / <alpha-value>)",
        },
        sidebar: {
          DEFAULT: "rgb(var(--sidebar-background-rgb) / <alpha-value>)",
          border: "rgb(var(--sidebar-border-rgb) / <alpha-value>)",
          foreground: "rgb(var(--sidebar-foreground-rgb) / <alpha-value>)",
          muted: "rgb(var(--sidebar-muted-rgb) / <alpha-value>)",
          hover: "rgb(var(--sidebar-hover-rgb) / <alpha-value>)",
        },
        brand: {
          orange: {
            50: "var(--brand-orange-50)",
            100: "var(--brand-orange-100)",
            200: "var(--brand-orange-200)",
            300: "var(--brand-orange-300)",
            400: "var(--brand-orange-400)",
            500: "var(--brand-orange-500)",
            600: "var(--brand-orange-600)",
            700: "var(--brand-orange-700)",
            800: "var(--brand-orange-800)",
            900: "var(--brand-orange-900)",
          },
          teal: {
            50: "var(--brand-teal-50)",
            100: "var(--brand-teal-100)",
            200: "var(--brand-teal-200)",
            300: "var(--brand-teal-300)",
            400: "var(--brand-teal-400)",
            500: "var(--brand-teal-500)",
            600: "var(--brand-teal-600)",
            700: "var(--brand-teal-700)",
            800: "var(--brand-teal-800)",
            900: "var(--brand-teal-900)",
          },
          amber: {
            400: "#fbbf24",
            500: "#f59e0b",
            600: "#d97706",
          },
          purple: {
            400: "#a78bfa",
            500: "#8b5cf6",
            600: "#7c3aed",
          },
        },
      },
    },
  },
  plugins: [heroui()],
};
